name: JAV Monitor

on:
  schedule:
    - cron: '*/300 * * * *'

  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Run Script
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: python monitor.py

    - name: Save seen.json
      run: |
        git config --global user.name github-actions
        git config --global user.email actions@github.com
        git add seen.json
        git commit -m "update seen" || echo "no changes"
        git push
